version: '3.4'

services:
  key-value-server:
    container_name: key-value-server
    image: issara
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8002:8000
  key-value-database:
    image: mysql:latest
    container_name: key-value-database
    expose:
      - 3306
    ports:
      - 3308:3306
    environment:
       MYSQL_DATABASE: 'key_value'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - database-volume-1:/var/lib/mysql
  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
volumes:
  database-volume-1: